# Generated by Django 5.1.3 on 2024-11-23 21:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Ad')),
                ('last_name', models.CharField(max_length=120, verbose_name='Soyad')),
                ('email', models.EmailField(max_length=254, validators=[django.core.validators.RegexValidator(message='Geçerli bir email adresi girin.', regex='^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\\.[a-zA-Z]{2,}$')], verbose_name='Email')),
                ('title', models.CharField(max_length=200, verbose_name='Başlık')),
                ('content', models.TextField(verbose_name='Kullanıcı Mesajı')),
                ('status', models.CharField(choices=[('OKUNMADI', 'Okunmadı'), ('OKUNDU', 'Okundu')], default='OKUNMADI', max_length=8)),
            ],
            options={
                'verbose_name': 'İletişim',
                'verbose_name_plural': 'Kullanıcı İletişimleri',
                'db_table': '',
                'managed': True,
            },
        ),
    ]
