# Generated by Django 5.1.3 on 2024-11-25 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Contact', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='contactmodel',
            table='contactmodel',
        ),
    ]
