# Generated by Django 5.1.3 on 2024-11-25 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Contact', '0003_contactmodel_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmodel',
            name='ip_address',
            field=models.GenericIPAddressField(default='', verbose_name='Kullanıcı Ip Adresi'),
        ),
    ]
