# Generated by Django 5.1.3 on 2024-12-08 12:19

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('User', '0014_alter_userprofile_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppointmentCreation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_is_active', models.BooleanField(default=True, verbose_name='Randevu Boş Mu ?')),
                ('date', models.DateField(verbose_name='Tarih: ')),
                ('time', models.TimeField(max_length=5, verbose_name='Saat')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
                ('staff_member', models.ForeignKey(limit_choices_to={'is_verified': True}, on_delete=django.db.models.deletion.CASCADE, related_name='appointments_as_staff', to='User.userprofile', verbose_name='Randevuyu veren kullanıcı')),
            ],
            options={
                'verbose_name': 'Randevular',
                'verbose_name_plural': 'Randevu Oluşturma',
                'db_table': 'appointment',
                'managed': True,
                'unique_together': {('staff_member', 'date', 'time')},
            },
        ),
        migrations.CreateModel(
            name='AppointmentDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_type', models.CharField(choices=[('Genel', 'Genel'), ('Ders', 'Ders'), ('Danışmanlık', 'Danışmanlık'), ('Sınav Hazırlığı', 'Sınav Hazırlığı'), ('Proje', 'Proje')], default='Genel', max_length=50, verbose_name='Randevu Türü ')),
                ('notes', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Beklemede', 'Beklemede'), ('Tamamlandı', 'Tamamlandı'), ('İptal Edildi', 'İptal Edildi'), ('Ertelendi', 'Ertelendi')], default='Beklemede', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('appointment_hour', models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(24)], verbose_name='Randevu Süresi (Saat)')),
                ('appointment_minut', models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(60)], verbose_name='Randevu Süresi (Dakika)')),
                ('appointment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='Appointments.appointmentcreation')),
                ('customer', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='appointments_as_customer', to='User.userprofile', verbose_name='Randevuyu alan kullanıcı')),
            ],
            options={
                'verbose_name': 'Randevu',
                'verbose_name_plural': 'Randevu Detayları',
                'db_table': 'appointment_details',
                'managed': True,
            },
        ),
    ]
