# Generated by Django 5.1.3 on 2024-12-08 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Appointments', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointmentcreation',
            options={'managed': True, 'ordering': ['id'], 'verbose_name': 'Randevular', 'verbose_name_plural': 'Oluşturulan Randevular'},
        ),
    ]
