# Generated by Django 5.1.3 on 2024-12-10 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appointments', '0002_alter_appointmentcreation_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointmentcreation',
            options={'managed': True, 'ordering': ['-id'], 'verbose_name': 'Randevular', 'verbose_name_plural': 'Oluşturulan Randevular'},
        ),
        migrations.AlterField(
            model_name='appointmentdetails',
            name='status',
            field=models.CharField(choices=[('Beklemede', 'Beklemede'), ('Onaylandı', 'Onaylandı'), ('İptal Edildi', 'İptal Edildi')], default='Beklemede', max_length=20),
        ),
    ]
