# Generated by Django 5.1.3 on 2024-11-23 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Bingöl Üniversitesi', max_length=70, verbose_name='Başlık')),
                ('description', models.TextField(verbose_name='Açıklama')),
            ],
        ),
    ]
