# Generated by Django 5.1.3 on 2024-11-23 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('About', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutpagemodel',
            options={'managed': True, 'verbose_name': 'Hakkımızda', 'verbose_name_plural': 'Hakkımızda Sayfa Ayarları'},
        ),
        migrations.AlterModelTable(
            name='aboutpagemodel',
            table='',
        ),
    ]
