# Generated by Django 5.1.3 on 2024-11-23 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('About', '0002_alter_aboutpagemodel_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageGalleryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='upload/site/%Y/%m/%d', verbose_name='Resim')),
            ],
            options={
                'verbose_name': 'Resim Galerisi',
                'verbose_name_plural': 'Resim Galerisi',
                'db_table': '',
                'managed': True,
            },
        ),
    ]
