# Generated by Django 5.1.3 on 2024-11-25 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0003_userprofile_is_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='is_verified',
            field=models.BooleanField(default=False, verbose_name='Kullanıcı yetkili mi ?'),
        ),
    ]
