# Generated by Django 5.1.3 on 2024-11-27 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0004_alter_userprofile_is_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, default='defaults/logo.jpg', null=True, upload_to='profile_pictures/', verbose_name='Kullanıcı Profil Resmi'),
        ),
    ]
