# Generated by Django 5.1.3 on 2024-12-01 18:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0010_institution_userprofile_institution'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='institution',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='User.institution'),
        ),
    ]
