# Generated by Django 5.1.3 on 2024-12-01 19:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0011_alter_userprofile_institution'),
    ]

    operations = [
        migrations.CreateModel(
            name='TitleModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Başlık')),
            ],
            options={
                'verbose_name': 'Başlık',
                'verbose_name_plural': 'Öğretim Görevlileri Başlıkları',
                'db_table': 'title_model',
                'managed': True,
            },
        ),
        migrations.AlterModelOptions(
            name='institution',
            options={'managed': True, 'ordering': ['-id'], 'verbose_name': 'Kurum', 'verbose_name_plural': 'Kurumlar'},
        ),
        migrations.AddField(
            model_name='userprofile',
            name='title',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='User.titlemodel'),
        ),
    ]
