# Generated by Django 5.1.3 on 2024-12-01 20:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0012_titlemodel_alter_institution_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='title',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='User.titlemodel'),
        ),
    ]
